services:
  spring-app:
    build: .
    container_name: spring-api-dogocorp
    restart: always
    ports:
      - "9090:8080"  # Mapeo: Puerto del Host (9090) -> Puerto del Contenedor (8080)
    environment:
      - SERVER_PORT=8080
      - TZ=America/Mexico_City # Ajusta a tu zona horaria para los logs
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - dogocorp-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dogocorp-net:
    external: true # Asumimos que ya tienes una red creada para tus otros servicios
